Set device as HeaterCooler instead of Thermostat.
dave-atx/homebridge-platform-smartac pull request #5
Opened 2018-06-22 03:08 UTC by DFurnes

Thanks for the fantastic plugin!!

I wanted to be able to tap the accessory in the Home app in order to turn on & off my air conditioner. Switching the service to be a [`HeaterCooler`](https://github.com/KhaosT/HAP-NodeJS/blob/a4f806d4eccf97cbb4995207e3225937b7622519/lib/gen/HomeKitTypes.js#L2990-L3007) seems to have done the trick.

After swapping that, I was also able to toggle the "state" from `COOLING` to `IDLE` based on whether the thermometer read lower than the target, so that the app would show the correct icon and verb:

<img width="302" src="https://user-images.githubusercontent.com/583202/41755755-eb17eb10-75a6-11e8-88a2-6c2d78f29458.jpeg">

2018-07-01 19:17 UTC, DFurnes commented
Added some error checking in 432adea, in case the thermostat is [broken](https://user-images.githubusercontent.com/583202/42137860-c0a59024-7d41-11e8-8a47-4f09b6f4b746.png):

<img width="236" src="https://user-images.githubusercontent.com/583202/42137835-7c6c24d6-7d41-11e8-999a-3eb15690d5fd.jpg">

2018-07-12 03:14 UTC, DFurnes commented
Updated for the new [mymodlet.com](http://mymodlet.com) in 5453fd7.

2018-07-16 00:45 UTC, Tecnico1931 commented
I got it working after installing https://github.com/cheeriojs/cheerio.

2018-07-17 02:01 UTC, DFurnes commented
It turns out the new website allows controlling the A/C when the thermostat is offline! I've updated this pull request's error checking in 9427bf0 to only error out with "No response" if the modlet itself is offline, and otherwise show "0°" for the current temperature to indicate if the thermostat is broken.

<img width="234" src="https://user-images.githubusercontent.com/583202/42792412-21976d5a-8943-11e8-83fc-6d200c774885.jpeg">

2018-09-03 17:06 UTC, picnicbob commented
Thanks for this. So far your branch is the only way I've found to get the modlet working with homebridge again after the web update.
I do have an issue now though that might be related to the HeaterCooler change, and I'm not sure if it's an Apple bug or if it's something we can fix:
**If an automation is run that should set the AC OFF it seems to toggle it instead, turning it ON if it is already OFF.**
Anyone else having this issue? I'm going to investigate a little bit today.

2018-09-03 17:14 UTC, picnicbob requested changes
I'm not sure how to do this myself or I would. Not a frequent user of GitHub.com

2018-09-03 17:14 UTC, picnicbob commented on index.js
> +      this.api.log(this.name, 'set heating / cooling active: ' + !this.powerOn);
setActiveState() is not necessarily always called to toggle, it can be called with the existing value. Use value instead of !this.powerOn

2018-09-03 17:14 UTC, picnicbob commented on index.js
> +      this.powerOn = !this.powerOn;
(Use value instead of !this.powerOn here too obviously)

2018-09-05 02:18 UTC, Tecnico1931 commented
getting an error


 (node:20890) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'deviceId' of undefined
    at status.SmartACs.forEach.ac (/usr/local/lib/node_modules/homebridge-platform-smartac/index.js:126:27)
    at Array.forEach (<anonymous>)
    at ThinkEcoAPI.getThermostats (/usr/local/lib/node_modules/homebridge-platform-smartac/index.js:122:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:20890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20890) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

2018-09-16 01:55 UTC, DFurnes commented
Oh, good catch @picnicbob! Fixed in cf3e48f.

2019-03-16 17:29 UTC, Tecnico1931 approved these changes

2019-04-11 01:34 UTC, matthew-gerstman commented
just wanna leave this command here if anyone is trying to install this branch

`npm install -g https://github.com/DFurnes/homebridge-platform-smartac#cf3e48f66fbd728fa33f670ad9053c4fab184ea6`

installs the plugin @DFurnes branch commit

2019-04-11 15:07 UTC, dave-atx commented
Apologies for the long absence -- I moved and don't have a AC unit that can use the SmartAC devices anymore. I'll merge this in and do a new release.

If anyone would like to take over stewardship of the project, please reach out.

2019-04-11 15:07 UTC, merged